task:
  name: LinuxGlibcAarch64
  only_if: $CIRRUS_BRANCH == 'master'
  only_if: $CIRRUS_RELEASE != ''
  env:
    GITHUB_TOKEN: ENCRYPTED[09aebd5de67bdb9b4fac7bad850ae6b2e2f4872d863c30b680dd7e8ef6d966b85bbb5589b44d5da20d39444cdf903431]
    CARGO_TERM_COLOR: always
  arm_container:
    image: fedora:latest
  prepare_script:
    - whoami
    - dnf check-update -q && dnf up -q -y
    - dnf group install -y "C Development Tools and Libraries" "Development Tools"
    - dnf in -y curl
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - . $HOME/.cargo/env
    - cargo install cargo-auditable cargo-audit
  build_script:
    - whoami
    - . $HOME/.cargo/env
    - ls -lah
    - rustc --version
    - cargo auditable build --release --locked
  hash_script:
    - whoami
    - ls -lah
    - cd target/release
    - mv cie cie-linux-glibc-aarch64
    - sha256sum cie-linux-glibc-aarch64 > sha256-cie-linux-glibc-aarch64
    - mv cie-linux-glibc-aarch64 ../../ && mv sha256-cie-linux-glibc-aarch64 ../../
  upload_script:
    - whoami
    - ls -lah
    - files_to_upload=($(ls | grep cie)); . ./upload.sh
      
task:
  name: LinuxMuslAarch64
  only_if: $CIRRUS_BRANCH == 'master'
  only_if: $CIRRUS_RELEASE != ''
  env:
    GITHUB_TOKEN: ENCRYPTED[09aebd5de67bdb9b4fac7bad850ae6b2e2f4872d863c30b680dd7e8ef6d966b85bbb5589b44d5da20d39444cdf903431]
    CARGO_TERM_COLOR: always
  arm_container:
    image: alpine:latest
  prepare_script:
    - apk -U upgrade
    - apk add curl make pkgconf bash build-base rust cargo
    - cargo install cargo-auditable cargo-audit
  build_script:
    - whoami
    - ls -lah
    - rustc --version
    - export PATH="$PATH:$HOME/.cargo/bin"
    - cargo auditable build --release --locked
  hash_script:
    - whoami
    - cd target/release
    - mv cie cie-linux-musl-aarch64
    - sha256sum cie-linux-musl-aarch64 > sha256-cie-linux-musl-aarch64
    - mv cie-linux-musl-aarch64 ../../ && mv sha256-cie-linux-musl-aarch64 ../../
  upload_script:
    - whoami
    - ls -lah
    - files_to_upload=($(ls | grep cie)); . ./upload.sh
    
task:
  name: FreebsdAmd64
  only_if: $CIRRUS_BRANCH == 'master'
  only_if: $CIRRUS_RELEASE != ''
  env:
    GITHUB_TOKEN: ENCRYPTED[09aebd5de67bdb9b4fac7bad850ae6b2e2f4872d863c30b680dd7e8ef6d966b85bbb5589b44d5da20d39444cdf903431]
    CARGO_TERM_COLOR: always
  freebsd_instance:
    image_family: freebsd-13-2
  prepare_script:
    - whoami
    - mkdir -p /usr/local/etc/pkg/repos
    - cp ./FreeBSD.conf /usr/local/etc/pkg/repos/
    - pkg update
    - pkg upgrade -y
    - pkg install -y curl pkgconf bash
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - . $HOME/.cargo/env
    - cargo install cargo-auditable cargo-audit
  build_script:
    - whoami
    - . $HOME/.cargo/env
    - ls -lah
    - rustc --version
    - cargo auditable build --release --locked
  hash_script:
    - whoami
    - cd target/release
    - mv cie cie-freebsd-amd64
    - sha256sum cie-freebsd-amd64 > sha256-cie-freebsd-amd64
    - mv cie-freebsd-amd64 ../../ && mv sha256-cie-freebsd-amd64 ../../
  upload_script:
    - whoami
    - ls -lah
    - files_to_upload=($(ls | grep cie)); . ./upload.sh
    
task:
  name: MacosxSilicon
  only_if: $CIRRUS_BRANCH == 'master'
  only_if: $CIRRUS_RELEASE != ''
  env:
    GITHUB_TOKEN: ENCRYPTED[09aebd5de67bdb9b4fac7bad850ae6b2e2f4872d863c30b680dd7e8ef6d966b85bbb5589b44d5da20d39444cdf903431]
    CARGO_TERM_COLOR: always
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  prepare_script:
    - whoami
    - NONINTERACTIVE=1 brew update
    - NONINTERACTIVE=1 brew outdated
    - NONINTERACTIVE=1 brew upgrade
    - NONINTERACTIVE=1 brew install pkg-config make curl coreutils
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - . $HOME/.cargo/env
    - cargo install cargo-auditable cargo-audit
  build_script:
    - whoami
    - . $HOME/.cargo/env
    - ls -lah
    - rustc --version
    - cargo auditable build --release --locked
  hash_script:
    - whoami
    - cd target/release
    - mv cie cie-macosx-silicon
    - sha256sum cie-macosx-silicon > sha256-cie-macosx-silicon
    - mv cie-macosx-silicon ../../ && mv sha256-cie-macosx-silicon ../../
  upload_script:
    - whoami
    - ls -lah
    - files_to_upload=($(ls | grep cie)); . ./upload.sh