settings:
  timezone: "utc" # Possible chocices are: utc | local | tzformat Like "Europe/Amsterdam"

to_remove:
  - 
    regex: "^STH"
    key: "SUMMARY"
  - 
    regex: "[a-b]"
    key: "SUMMARY"

to_move:
  - 
    regex: "[a-b]"
    key: "SUMMARY"
    weekday: "Tue"