name: Release for Linux glibc amd64

on:
  push:
    tags:
      - '*'
      
env:
  CARGO_TERM_COLOR: always

jobs:
  publish_for_linux_glibc_amd64:
    name: Release for Linux glibc amd64
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: |
          whoami
          dnf group install -y "C Development Tools and Libraries" "Development Tools"
          dnf in -y curl go
          go version
          go build -ldflags="-s -w" -o cie-linux-glibc-amd64
          sha256sum cie-linux-glibc-amd64 > sha256-cie-linux-glibc-amd64
          
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: cie-linux-glibc-amd64 
        asset_name: cie-linux-glibc-amd64 
        tag: ${{ github.ref }}
    - name: Upload checksum to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: sha256-cie-linux-glibc-amd64
        asset_name: sha256-cie-linux-glibc-amd64
        tag: ${{ github.ref }}
