name: Release for Linux glibc amd64

on:
  push:
    tags:
      - '*'
      
env:
  CARGO_TERM_COLOR: always

jobs:
  publish_for_linux_glibc_amd64:
    name: Release for Linux glibc amd64
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: |
          whoami
          dnf group install -y "C Development Tools and Libraries" "Development Tools"
          dnf in -y curl
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          . $HOME/.cargo/env
          cargo install cargo-auditable cargo-audit
          rustc --version
          cargo auditable build --release --locked
          cd target/release
          mv cie cie-linux-glibc-amd64
          sha256sum cie-linux-glibc-amd64 > sha256-cie-linux-glibc-amd64
          
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/cie-linux-glibc-amd64 
        asset_name: cie-linux-glibc-amd64 
        tag: ${{ github.ref }}
    - name: Upload checksum to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/sha256-cie-linux-glibc-amd64
        asset_name: sha256-cie-linux-glibc-amd64
        tag: ${{ github.ref }}