name: Release for MacOS X amd64

on:
  push:
    tags:
      - '*'
      
env:
  CARGO_TERM_COLOR: always

jobs:
  publish_for_macosx_amd64:
    name: Release for MacOS X amd64
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: |
          whoami
          brew install coreutils go
          go version
          go build -ldflags="-s -w" -o cie-macosx-amd64
          sha256sum cie-macosx-amd64 > sha256-cie-macosx-amd64
          
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: cie-macosx-amd64
        asset_name: cie-macosx-amd64
        tag: ${{ github.ref }}
    - name: Upload checksum to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: sha256-cie-macosx-amd64
        asset_name: sha256-cie-macosx-amd64
        tag: ${{ github.ref }}
